# Generated by Django 5.0.4 on 2024-04-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=150)),
                ('item_desc', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
