# Generated by Django 5.0.4 on 2024-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('book_name', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_photo', models.ImageField(upload_to='covers/')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
